export const stupidID = "1095422079362404456";
export const stupid = `<:stupid:${stupidID}>`;
export const neuralizer = "<:mibneuralyzer:959135586357215314>";
export const eopt = "https://media.tenor.com/2fgXC4Ji9qEAAAAC/eopt-pt.gif";
export const devops = `I'd just like to interject for a moment. What you're referring to as DevOps, is in fact, DevOps culture, or as I've recently taken to calling it, the culture of collaboration. DevOps is not a standalone role, but rather a cultural approach to software development and operations that emphasizes collaboration, communication, and automation.\n\nMany organizations adopt the principles of DevOps culture without realizing it. Through a peculiar turn of events, the term DevOps is often used to describe a combination of practices, tools, and mindset that promote closer collaboration between development and operations teams, and enable faster and more reliable software delivery.\n\nThere really is DevOps, and these organizations are embracing it, but it is just a part of the overall software development and operations ecosystem. DevOps is the mindset: the approach in the organization that brings together development and operations teams to work together seamlessly. DevOps is an essential part of modern software delivery, but it cannot exist in isolation; it requires a holistic adoption of the culture and practices across the entire organization. DevOps is normally practiced in combination with agile methodologies and continuous integration/continuous delivery (CI/CD) pipelines.\n\nSo, remember, when you talk about DevOps, you're not just referring to a single role or position, but rather a cultural transformation that drives collaboration and efficiency in software development and operations. DevOps is not a role, it's a culture!`;
export const linux = `I'd just like to interject for a moment. What you're refering to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.\n\nMany computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called Linux, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.\n\nThere really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions of GNU/Linux!`;
export const anonymous =
	"https://media.discordapp.net/attachments/1088232532807520417/1133018342643466311/4fba7a226c1e361a9bbfe4df1a00226b2d90efcf5ce5801832e0646b4e332a52_1.jpg";
export const wed4pm =
	"https://tenor.com/view/firmo-rafa-joao-lucas-semana-gif-26439293";
export const nani =
	"https://tenor.com/view/dk-nintendo-donkey-kong-gif-23203423";
export const firebase = "https://tenor.com/view/asd-gif-21458128";
export const feijoada =
	"https://cdn.discordapp.com/attachments/1088232532807520417/1149048671120396288/Feijoada-3071114142.jpg";
export const bun = "have you guys seen https://bun.sh/ ? Looks promising....";
export const cLigaMeu =
	"https://media.discordapp.net/attachments/1131226059115872367/1164905390803263498/c-lica-meu.jpeg";
